server:
  port: 8815

spring:
  application:
    name: stock
  cloud:
    nacos:
      #nacos
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
        ephemeral: false #永久实际